command: ExtractSCF # [ExtractSCF, Evaluate, RunStatistcs]

reader:
  module: XmlFile # [SentenceDatabaseCorpus, ExampleDatabaseCorpus, PalavrasFileCorpus, NILCLexicon, XmlFile, RaspFileCorpus]
  database:
    engine: mysql 
    host: localhost
    user: root
    password: zanette
    dbName: scf-cardiologia
  databaseReader:
    pageSize: 100 
  fileReader:
    path: /home/adriano/src/verbnet-3.2/
    #path: /home/adriano/src/verbnet_examples.dep
    #path: /home/adriano/src/lexicoNilc.txt

extractor:
  module: Verbnet # [SintaticRaspDependency, SemanticFrames, PalavrasDependency, NILCLexicon, Verbnet, Framenet]

builder:
  module: ReferenceFrames # [SCF, SemanticFramesDatabase, , ReferenceFrames]
  order: position # [position, relevance]
  database:
    engine: mysql
    host: localhost
    user: root
    password: zanette
    dbName: scf-english
    scfReferenceTable: verbnet_frames
  ignoreClasses: ['REFL', 'PR', 'OCL', 'DAT', 'ADJP', 'ADVP', 'AUX']
  extractArguments: false
  createTables: false
  clearTables: true

statistics:
  modules: ['frequency'] #['frequency', 'power-law', 'loglikelihood', 't-score']

filter:   
  columns: ['frequency','verbFrequency', 'isPassive'] #['verbFrequency', 'frequency', 'relativeFrequency', 'frameFrequency']
  values: [3, 115, 1]
  operators: ['<','<', '=']

evaluator:
  scfReferenceTable: nilc_frames
  filter: relativeFrequency
  verbList: []
  minValue: 0.008
  maxValue: 0.009
  increment: 0.0001
  operator: '<' 
  #output: '/home/adriano/relative.jpg'
  output: ''