command: ExtractSCF # [ExtractSCF]

reader:
  module: XmlFile # [SentenceDatabaseCorpus, ExampleDatabaseCorpus, PalavrasFileCorpus, NILCLexicon, XmlFile]
  database:
    engine: mysql 
    host: localhost
    user: root
    password: zanette
    dbName: childes
  databaseReader:
    pageSize: 100 
  fileReader:
    path: /home/adriano/src/fndata-1.5/lu/lu2.xml

extractor:
  module: Framenet # [SintaticRaspDependency, SemanticFrames, PalavrasDependency, NILCLexicon, Verbnet, Framenet]

builder:
  module: VerbnetFrames # [SCF, SemanticFramesDatabase, VerbnetFrames, NILCLexicon]
  order: position # [position, relevance]
  database:
    engine: mysql
    host: localhost
    user: root
    password: zanette
    dbName: scf-teste
    scfTable: framenet_frames
  ignoreClasses: ['AUX', 'SUBJ']
  extractArguments: true
  createTables: false
  clearTables: true

statistics:
  run: true
  modules: ['frequency', 'power-law', 'loglikelihood', 't-score']

filter:
  absoluteFrequencyVerb: 5
  absoluteFrequencyFrame: 5
  relativeFrequency: 10
  alpha: 0.5




