command: ExtractSCF # [ExtractSCF, Evaluate, RunStatistcs]

reader:
  module: PalavrasFileCorpus # [SentenceDatabaseCorpus, ExampleDatabaseCorpus, PalavrasFileCorpus, NILCLexicon, XmlFile]
  database:
    engine: mysql 
    host: localhost
    user: root
    password: zanette
    dbName: scf-cardiologia
  databaseReader:
    pageSize: 100 
  fileReader:
    path: /home/adriano/src/cardiologia/
    #path: /home/adriano/src/lexicoNilc.txt

extractor:
  module: PalavrasDependency # [SintaticRaspDependency, SemanticFrames, PalavrasDependency, NILCLexicon, Verbnet, Framenet]

builder:
  module: SCF # [SCF, SemanticFramesDatabase, , ReferenceFrames]
  order: relevance # [position, relevance]
  database:
    engine: mysql
    host: localhost
    user: root
    password: zanette
    dbName: scf-cardiologia
    scfReferenceTable: nilc_frames
  ignoreClasses: ['V', 'SUBJ', 'REFL', 'PR', 'ADJP', 'SINF']
  extractArguments: false
  createTables: false
  clearTables: true

statistics:
  modules: ['frequency', 'loglikelihood', 't-score'] #['frequency', 'power-law', 'loglikelihood', 't-score']

filter: 
  #columns: ['verbFrequency', 'frequency', 'relativeFrequency', 'frameFrequency']
  #values: [0, 0, 0, 0.5]
  #operators: ['<', '<', '<', '<']
  columns: ['verbFrequency', 'frequency']
  #values: [100, 2]
  #verb 81, 114, 172
  #f: 2, rf: 0.008, vf:114, p: 0.644444444444, r: 0.537037037037, f: 0.585858585859
  #f: 4, rf: 0.008, vf: 172, p: 0.574074074074, r: 0.607843137255, f: 0.590476190476 
  values: [172, 4]
  operators: ['>', '>']

evaluator:
  scfReferenceTable: nilc_frames
  filter: relativeFrequency
  verbList: []
  minValue: 0.001
  maxValue: 0.041
  increment: 0.0001
  operator: '>' 
  #output: '/home/adriano/relative.jpg'
  output: ''