command: Evaluate # [ExtractSCF, Evaluate, RunStatistcs]

reader:
  module: NILCLexicon # [SentenceDatabaseCorpus, ExampleDatabaseCorpus, PalavrasFileCorpus, NILCLexicon, XmlFile]
  database:
    engine: mysql 
    host: localhost
    user: root
    password: zanette
    dbName: scf-cardiologia
  databaseReader:
    pageSize: 100 
  fileReader:
    #path: /home/adriano/src/cardiologia/
    path: /home/adriano/src/lexicoNilc.txt

extractor:
  module: NILCLexicon # [SintaticRaspDependency, SemanticFrames, PalavrasDependency, NILCLexicon, Verbnet, Framenet]

builder:
  module: ReferenceFrames # [SCF, SemanticFramesDatabase, , ReferenceFrames]
  order: position # [position, relevance]
  database:
    engine: mysql
    host: localhost
    user: root
    password: zanette
    dbName: scf-cardiologia
    scfReferenceTable: nilc_frames
  ignoreClasses: ['V', 'SUBJ', 'REFL', 'PR', 'ADJP', 'SINF']
  extractArguments: true
  createTables: false
  clearTables: false

statistics:
  modules: ['frequency', 'loglikelihood', 't-score'] #['frequency', 'power-law', 'loglikelihood', 't-score']

filter: 
  #columns: ['verbFrequency', 'frequency', 'relativeFrequency', 'frameFrequency']
  #values: [0, 0, 0, 0.5]
  #operators: ['<', '<', '<', '<']
  columns: ['verbFrequency', 'frequency']
  values: [50, 5]
  operators: ['>', '>', '>']

evaluator:
  scfReferenceTable: nilc_frames
  filter: relativeFrequency
  verbList: []
  minValue: 0.001
  maxValue: 0.4
  increment: 0.01
  operator: '>' 
  #output: '/home/adriano/relative.jpg'
  output: ''